# Generated by Django 2.2.1 on 2019-06-11 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comid', models.BigIntegerField()),
                ('fdate', models.CharField(max_length=80)),
                ('resolution', models.CharField(max_length=80)),
                ('gnis_id', models.CharField(max_length=80)),
                ('gnis_name', models.CharField(max_length=80)),
                ('lengthkm', models.FloatField()),
                ('reachcode', models.CharField(max_length=80)),
                ('flowdir', models.CharField(max_length=80)),
                ('wbareacomi', models.BigIntegerField()),
                ('ftype', models.CharField(max_length=80)),
                ('fcode', models.BigIntegerField()),
                ('shape_leng', models.FloatField()),
                ('enabled', models.CharField(max_length=80)),
                ('gnis_nbr', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Rivers',
            },
        ),
    ]
