# Generated by Django 2.2.2 on 2019-06-16 13:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comid', models.BigIntegerField()),
                ('reachcode', models.CharField(max_length=80)),
                ('flowdir', models.CharField(max_length=80)),
                ('wbareacomi', models.BigIntegerField()),
                ('ftype', models.CharField(max_length=80)),
                ('streamorde', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Rivers',
            },
        ),
    ]
